#!/bin/bash
alias python=/usr/bin/python3
sudo apt-get install -y gcc g++ gfortran build-essential git wget linux-image-generic libopenblas-dev python3-dev python3-pip python3-nose python3-numpy python3-scipy
alias python=/usr/bin/python3  
sudo apt-get install python-numpy
sudo pip3 install Theano
sudo pip3 install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt
sudo pip3 install Lasagne==0.1
sudo pip3 install nltk
sudo pip3 install sklearn


